### ISSUE TITLE
Inconsistent UInt160 hashes

### ISSUE THREAD

**Issue by lock9** [neo-project/neo-express#276]
Hi.

The script hash shown by Neo Express / VS Code extensions seems incorrect. 
![image](https://user-images.githubusercontent.com/38396062/231208586-f54d8693-bd6a-4825-8d4d-e467d4366182.png)

This is not the correct hash for the contract. The value should be 0x72a951129962cc3dec0220558c7f1064367d395b instead.

**Comment by gsmachado** [comment]
@devhawk do we have a unified view of how Hashes should be represented in a readable way? I mean, big- versus little-endian-kind-of-thing.

**Comment by gsmachado** [comment]
@lock9 in my point there's no right or wrong way. This is just representation, and the ecosystem should just agree (standardize) on a way how to display or input these.

Or am I wrong?

**Comment by gsmachado** [comment]
IMHO, this directly relates to https://github.com/neo-project/neo/issues/938.

FYI, @roman-khimov

**Comment by lock9** [comment]
> @lock9 in my point there's no right or wrong way. This is just representation, and the ecosystem should just agree (standardize) on a way how to display or input these.
> 
> Or am I wrong?

It must be consistent across the applications. The problem here is that it even suggests you to copy the script hash - but the value is not usable as is, you need to revert it. Who could possibly imagine such a thing? It's not even 'explainable'

**Comment by gsmachado** [comment]
> It must be consistent across the applications.

Yes, agree.

> The problem here is that it even suggests you to copy the script hash

Yes, that's a usability problem.

> but the value is not usable as is, you need to revert it

Depends on where you want to paste, and which representation the application you want to paste accepts it. Big-endian? Little-endian?

> Who could possibly imagine such a thing?

Seniors could imagine such a thing ([here](https://en.wikipedia.org/wiki/Endianness)), but definitely not newbies or people learning it. 😓 

> It's not even 'explainable'

It's explainable, but not usable. Two different things.

**Comment by gsmachado** [comment]
IMHO, this is not only a problem of `neo-express`.

It's a problem within our entire community on how to standardize hash inputs and things like that. It's just more visible in `neo-express` because it's a tool that which multiple tools interact.

If I get a hash output somewhere in neow3j and paste it to another tool, I'm almost certain that I'd need to reverse it in some scenarios. 😓

**Comment by lock9** [comment]
> Depends on where you want to paste, and which representation the application you want to paste accepts it. Big-endian? Little-endian?

I want to paste it in my Neo express scripts. That is why it's not consistent. 

It says that the hash of the contract is "A", but if I try to use "callContract(A)", it won't work.

**Comment by melanke** [comment]
I agree that a breaking change is something we should avoid, but I also agree that we need to be as clear and concise as possible, specially integrating our tools.

I suggest to introduce a new symbol as prefix for little-endian. NeoExpress could keep using little-endian as default when no prefix symbol is provided but show a warning message to ask the user to use the correct symbol and warn that it will use little-endian as default.

**Comment by devhawk** [comment]
> I suggest to introduce a new symbol as prefix for little-endian. NeoExpress could keep using little-endian as default when no prefix symbol is provided but show a warning message to ask the user to use the correct symbol and warn that it will use little-endian as default.

This sounds like a reasonable idea, though I'd like to get more feedback from the folks on this thread. In particular, I'm interested in what @lock9 thinks. The suggestion here is to make the tools easier to use, but having a two different prefix characters - `#` for reversed and something else for non-reversed - seems as hard to explain as the current situation.

[`ContractParameterParser.ParseStringParameter`](https://github.com/ngdenterprise/neo-blockchaintoolkit-library/blob/master/src/bctklib/ContractParameterParser.cs#L273) (used across BCTK) already looks for the following prefixes:

* `@`: parse the string as an address. The string can be a wallet name from the .neo-express file (i.e. `@alice`) or an encoded address (i.e. `@NZS7VMxxu9H9db1fPGQCWeEj4z7dagFoLm`)
* `#`: parse the string as a hash. The string can be a reverse encoded UInt160 or UInt256 (using `TryParse` as described above) or it can be the name of contract (such as `#NeoToken`)
* `file://`: parse the string as a path to an on disc file
* `0x': parse the string as hex encoded

Note, adding a new prefix for "non reversed hex encoded hash" is a minor breaking change. Anyone already using that character in their invoke files or other invocation scripts runs the risk of their project breaking since a string that was previously treated as a simple string would now be treated as a hash. However, using a punctuation character such as `$` or `%` - or even a multi character prefix such as `##` would make the risk pretty low. 

Furthermore, if a prefixed string can't be parsed into the expected type, it gets treated as a simple string. For example, `#foo` is parsed as a string parameter (assuming there is no `foo` contract). So `##5b397d3664107f8c552002ec3dcc62991251a972` would be treated as a non-reversed hex string but `##hello` would still be treated as a simple string parameter.

**Comment by lock9** [comment]
Some context:
We made our smart contract development course using 2 contracts. The first one is the token contract, and the second one is the NFT contract. To mint an NFT, the user must send the tokens to the contract, triggering the onNEP17Transfer method.  The user must recompile and deploy the contract several times, one for each step in the tutorial.  

In this scenario:
- The user collects the script hash from the first contract and adds it to the transfer callback.  To do this, the user would open the explorer tab, find his contract, copy the hash, and put it inside his contract. 
- The user will send the funds from his account to the NFT contract hash, so he needs the contract hash again.
- The user can view the storage contents using the hash

The problem:
If they use the script hash being shown by the extension, 2 things will happen: 
1 - The funds will be transferred to the incorrect account
2 - The callback won't be triggered (since the hash was incorrect)
3 - The storage is still visible using the incorrect key, but using the same key inside a contract or tool will not work. 

Notes:
We had to change and rework several steps to make the development more 'acceptable'. For example: we started with simple methods like 'symbol'. However, we had to change it. The response is encoded in hex and is not human-readable. In general, there are several this we have to make up to avoid explaining complex topics right at the beginning. 

We also use the tool in Python, Java, and other programming languages. I'm not sure if all of them have the same SDK features available or have similar names.

Urgent solution:
This problem of copying the script hash is extremely urgent. I propose that both the big-endian and little-endian versions of the script hash be displayed inside the extension. 
Everything inside the extension drives you to use one value, while the code expects a different one. We should at least allow them to view the correct one. This won't fix the issue of 'deceiving' the user into thinking that the keys on the debugger and the storage views are correct.

For the future:
There are a ton of things that we need to improve. I've personally reworked the tutorial 5 times already due to inconsistencies in naming, conversions, features etc. Things won't work if the user walks 1 meter outside the trail. 
I believe many of them were reported as issues on GitHub. I didn't open issues for everything but a few important ones. 

My concerns about prefixes and others:
We need these values to be used inside the contracts and not only inside scripts. I think we need it, but at the same time, it's not the main issue.  


The alternative for us is to use the command line, but this has also been a challenge because of inconsistencies in the command line tool.

**Comment by gsmachado** [comment]
@devhawk @JohndeVadoss any opinions/comments on the comment above?

It seems it negatively affects https://github.com/AxLabs/grantshares/issues/11, in specific if you read https://github.com/AxLabs/grantshares/issues/11#issuecomment-1567270007 and https://github.com/AxLabs/grantshares/issues/11#issuecomment-1503649986.

**Comment by devhawk** [comment]
> I propose that both the big-endian and little-endian versions of the script hash be displayed inside the extension.

I'm sure this would work fine for instructor led tutorials, but how will a developer using these tools for the first time know which one to use? 

> Everything inside the extension drives you to use one value, while the code expects a different one

So can we simply standardize the toolkit to always display UInt160/256 values as reverse encoded hex?

**Comment by lock9** [comment]
I think the second option is better. I don't think we ever use script hashes in current format

**Comment by lock9** [comment]
Will it work inside smart-contracts? Can you paste 'NiHURyS83nX2mpxtA7xq84cGxVbHojj5Wc' inside the code? It can be a good solution if smart contracts can use this value inside it. 

I think we need to revert it because it's inconsistent inside Neo Express. If you copy the value from the explorer and paste it inside a invoke file, it won't work. This must be fixed by replacing the existing hash or showing the reverted one.
It won't work if you copy the value and paste it on Dora, One Gate, or try to use it as a parameter.

Since almost everywhere we need it reverted, we need to show this value somewhere.

**Comment by roman-khimov** [comment]
It [works like this](https://github.com/nspcc-dev/neo-go/blob/9a15d2d781116a58ea05b0515660e136ff865aab/examples/token/token.go#L16) for us in smart contracts: 
```
	owner = address.ToHash160("NbrUYaZgyhSkNoRo9ugRyEMdUZxrhkNaWB")
```
This gets compiled into
```
2        PUSHDATA1    aed8db3b5d664ca04bdd7bed37992ff958560b41
24       CONVERT      Buffer (30)
26       STSFLD0      
```
(conversion is made just because `Hash160` is [in fact](https://pkg.go.dev/github.com/nspcc-dev/neo-go/pkg/interop#Hash160) a `[]byte`).

**Comment by lock9** [comment]
I think that if everyone agrees, we can move to an address in the future. Before we have that, could we revert the hex inside the extension? Or at least have an option to view it reverted?

**Comment by csmuller** [comment]
> I think that if everyone agrees, we can move to an address in the future. Before we have that, could we revert the hex inside the extension? Or at least have an option to view it reverted?

I agree with @lock9, we should quickly get a solution in the VSCode extension that provides the reverted hex, which can be used without modification (i.e., reverting). If the user can copy the script hash from the UI and paste it back somewhere in the same tool, it should just work. This might seem like a minor thing in the context of the extension, but I think it's a big pain point if you have to tell the user "copy the hash, then go to this converter page, reverse it and paste it back in the same tool, just because".

**Comment by gsmachado** [comment]
While we were all discussing, I took my fun time and already implemented it:

https://github.com/ngdenterprise/neo3-visual-tracker/pull/163

I hope this would ALLEVIATE the issue -- because it doesn't solve it for good.

**Comment by ixje** [comment]
Shouldn't we fix the all tools using the wrong order for input instead? Now the user is still in a guessing game because 99% don't have a clue what order should be provided (depending on the tool I'm part of that 99%)

**Comment by lock9** [comment]
@ixje I think we should. There are other places where we are showing the incorrect 'hash'.

**Comment by PazBazak** [comment]
Any updates regarding this ticket... its been a long time and as a newb getting in, the extension was confusing.

**Comment by cschuchardt88** [comment]
@PazBazak No update. We are working on something else to replace _(in future)_. However there shouldn't be a problem in `neoxp.exe` _(if you are using the command-line)_.

**Comment by lock9** [comment]
Hi,

This is not important anymore. We are using other tools. I'm going to close it.
